spring.application.name=quipu
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.s3.path-style-access-enabled=true

quipu.dynamodb.jobs-table=csv-processing-jobs
